export enum errorCodeUser {
    InvEmail = 'InvEmail',
    InvUser = 'InvUser',
    InvName = 'InvName',
    NoUser = 'NoUser',
    NoEmail = 'NoEmail',
    ExistEmail = 'ExistEmail',
    ErrLogin = 'ErrLogin',
    InvPass = 'InvPass',
    InvPassLength = 'InvPassLength',
    InvPassNumbers = 'InvPassNumbers',
    InvPassLetters = 'InvPassLetters',
    InvPassUpper = 'InvPassUpper',
    InvPassLower = 'InvPassLower',
    NoPass = 'NoPass',
    MongoError = 'MongoError',
}